### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by SyncGit12** [JordanSantiagoYT/FNF-JS-Engine#562]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

![image](https://github.com/user-attachments/assets/909c362a-afe8-4d91-a6b4-e10a9ca796c9)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

IM JUST CHARTING

**Comment by PatoFlamejanteTV** [comment]
Ok, did you put a mod or something? Can you send me the chart for testing purposes? Did you insert a "Random Shake" notes event?

**Comment by PatoFlamejanteTV** [comment]
Okay, **I think I understand, but I need to have your code you used to be sure** _(send your mod, that could be a glitch in events/engine_).

There is a function - called _GetRandomInt_
But one of his value, it's **nil.**
**So that is giving error because the "nil" value**

A time ago, **a guy had the same problem:**
> Don't surround getRandomInt with ' ' because it's not a string

Btw, "IM JUST CHARTING" inst just enough to understand the error.

Sources:
https://github.com/ShadowMario/FNF-PsychEngine/issues/5423
(https://github.com/ShadowMario/FNF-PsychEngine/issues/5423#issuecomment-1046265010)

**Comment by PatoFlamejanteTV** [comment]
Bro?

**Comment by PatoFlamejanteTV** [comment]
3 days without return is crazy

**Comment by SyncGit12** [comment]
helo
i was on filscrn
and got
error
and
icouldntcloseit

**Comment by SyncGit12** [comment]
what was i trying to say
