### ISSUE TITLE
Fix the multiple character script

### ISSUE THREAD

**Issue by mdk-pie** [JordanSantiagoYT/FNF-JS-Engine#663]
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Ive said this a ton of times already but like, jordan santiago, there is a specific version of js that the multiple character script works in which is JSE: v1.20.1 and for some reason any versions after that the holds notes in bfs side break for some reason i dont really know why, and tons of people dont use the new multiple character scripts since it isnt public i think and that also still breaks for some reason.

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Just use the multiple character script and make the bfs side have hold notes and the opponents will sing for some reason

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by PatoFlamejanteTV** [comment]
Uhhh, can you send the script to me check if the code is valid? Btw, (normally) script/mod-breaking updates fixing is really easy if your code is idk, well documented

**Comment by PatoFlamejanteTV** [comment]
I found some results when searching "multiple character script":

"Multiple characters for Lua | Psych Engine" - [https://gamebanana.com/tools/8427](https://gamebanana.com/tools/8427)

"Extra Char. Script in Psych Engine" - https://gamebanana.com/tools/11727

**Comment by JordanSantiagoYT** [comment]
quoted this from an older multichar script issue i found:

IVE FOUND THE ISSUE WITH YOUR MULTICHARACTER SCRIPTS NOT WORKING IN NEWER VERSIONS

it's because your version of the multicharacter script is outdated. newer versions of the script have it fixed, the creator also literally pointed out that issue. if you don't want to update the script anyway, go into your multicharacter script and delete ALL mentions of "name_of_notetype2" as otherwise it'll either hit every note (or in the case of newer versions of jse, trigger the animation ONLY when a sustain note is hit)

**Comment by mdk-pie** [comment]
thank you so much bro it actually worked
